---
do_token: "{{ lookup('env', 'DO_TOKEN') }}"
ssh_pub: "{{ lookup('env', 'SSH_PUBLIC_KEY') }}"
ssh_private: "{{ lookup('env', 'SSH_PRIVATE_KEY') }}"
project_name: "{{ lookup('env', 'PROJECT_NAME') }}"
key_name: "{{ project_name }} key"