---
# deploy infrastructure
- hosts: localhost
  gather_facts: false
  connection: local
  roles:
    - role: digitalocean

# build applications
- hosts: localhost
  gather_facts: false
  connection: local
  roles:
    - role: buildms
  vars_files:
    - ./vars/versions.yml
  tags:
    - build

# deploy applications on hosts
- hosts: do
  gather_facts: false
  roles:
    - role: deployms
  vars_files:
    - ./vars/versions.yml
  tags:
    - deploy
