---
# deploy infrastructure
- hosts: localhost
  gather_facts: false
  connection: local
  roles:
    - role: digitalocean

# build applications
- hosts: localhost
  gather_facts: false
  connection: local
  roles:
    - role: buildmc
  vars_files:
    - ./vars/versions.yml

# deploy applications on hosts
- hosts: localhost # do
  gather_facts: false
  connection: local
  roles:
    - role: deploymc
  vars_files:
    - ./vars/versions.yml
