---
- hosts: localhost
  gather_facts: false
  connection: local

  tasks:
    - name: Create ssh key
      community.digitalocean.digital_ocean_sshkey:
        oauth_token: "{{ do_token }}"
        name: "{{ key_name  }}"
        ssh_pub_key: "{{ ssh_pub }}"
        state: present
      register: ssh_key_result

    - name: Create a new droplet
      community.digitalocean.digital_ocean_droplet:
        state: present
        name: "{{ project_name }}-microservices"
        oauth_token: "{{ do_token }}"
        size: s-1vcpu-1gb
        region: fra1
        image: docker-20-04
        wait_timeout: 500
        ssh_keys:
          - "{{ ssh_key_result.data.ssh_key.fingerprint }}"
          - "0c:c0:21:2e:20:47:f8:58:b3:f9:24:85:33:bd:3b:82" # TODO: добавить переменную окружения, в которой будут лежать ключи для администрирования
      register: droplet

    # - debug:
    #     msg: "ID is {{ my_droplet.data.droplet.id }}, IP is {{ my_droplet.data.ip_address }}"
