version: "3.9"
services:
  ansible:
    build: .
    container_name: ansible
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./.cache:/app/.cache
      - ./ssh:/app/ssh
    env_file:
      - ./.env
    # command: ./run.sh

    # For Debug
    # stdin_open: true
    # tty: true
