version: "3.9"
services:
  ansible:
    build: .
    container_name: ansible
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./.cache:/app/.cache
    # For Debug
    # stdin_open: true
    # tty: true
