---

# build applications
- hosts: localhost
  gather_facts: false
  connection: local
  roles:
    - role: buildms
  vars:
    apps:
      - name: "{{ app_name }}"
        version: "{{ app_version }}"
        repo: "{{ app_repo }}"
  tags:
    - build

# deploy applications on hosts
- hosts: do
  gather_facts: false
  roles:
    - role: deployms
  vars:
    apps:
      - name: "{{ app_name }}"
        version: "{{ app_version }}"
        repo: "{{ app_repo }}"
  tags:
    - deploy
