---

- name: Fetch docker image archive
  ansible.builtin.copy:
    src: "{{ cache_folder }}/{{ item.name }}.tar"
    dest: "{{ item.name }}.tar"
    mode: '0644'
  loop: "{{ apps }}"

- name: install pip3
  ansible.builtin.apt:
    name: python3-pip
    state: present
    update_cache: yes

- name: Install Docker Module for Python
  ansible.builtin.pip:
    name: docker
    state: present

- name: Unpack docker image from archive
  community.docker.docker_image:
    name: "{{ item.name }}"
    tag: "{{ item.version }}"
    load_path: "{{ item.name }}.tar"
    state: present
    source: load
  loop: "{{ apps }}"

- name: Create docker-compose.yml
  ansible.builtin.template:
    dest: "docker-compose.yml"
    src: "docker-compose.yml.j2"

- name: Install compose
  ansible.builtin.pip:
    name: docker-compose
    state: present

- name: Compose up
  community.docker.docker_compose:
    project_src: "."
    build: no
