---
- name: Create ssh key
  community.digitalocean.digital_ocean_sshkey:
    oauth_token: "{{ do_token }}"
    name: "{{ key_name  }}"
    ssh_pub_key: "{{ ssh_pub }}"
    state: present
  register: ssh_key_result
  tags:
    - ssh

- name: Create a new droplet
  community.digitalocean.digital_ocean_droplet:
    state: present
    unique_name: true
    name: "{{ project_name }}-microservices"
    oauth_token: "{{ do_token }}"
    size: s-1vcpu-1gb
    region: fra1
    image: docker-20-04
    tags: "{{ project_name }}"
    wait_timeout: 500
    ssh_keys:
      - "{{ ssh_key_result.data.ssh_key.fingerprint }}"
      - "0c:c0:21:2e:20:47:f8:58:b3:f9:24:85:33:bd:3b:82" # TODO: добавить переменную окружения, в которой будут лежать ключи для администрирования
  tags:
    - vps
  register: droplet
