---

- name: Fetch docker image archive
  ansible.builtin.copy:
    src: "{{ cache_folder }}/{{ item.name }}.tar"
    dest: "{{ item.name }}.tar"
    mode: '0644'
  loop: "{{ apps }}"

- name: Unpack docker image from archive
  community.docker.docker_image:
    name: "{{ item.name }}"
    tag: "{{ item.version }}"
    load_path: "{{ item.name }}.tar"
    state: present
    source: load
  loop: "{{ apps }}"

- name: Compose up
  community.docker.docker_compose:
    project_src: "{{ role_path }}/files"

