# deploy only single microservice
version: "3.9"
services:
  ansible:
    command: ansible-playbook all.yml --tags "build,deploy" -i production.ini -i do_hosts.yml -v --extra-vars "app_name=$NAME app_version=$VERSION app_repo=$REPO"
