---

- name: Create cache folder
  file:
    path: "{{ cache_folder }}"
    state: directory

- name: Create SSH private key
  ansible.builtin.copy:
    content: "{{ ssh_private }}\n"
    dest: "{{ cache_folder }}/ssh_private_key"
    mode: '0600'
  register: ssh_private_key
  tags:
    - build

- name: Create folder for source
  ansible.builtin.file:
    path: "{{ cache_folder }}/{{ apps[0].name }}"
    state: directory
    recurse: yes
  register: git_folder
  tags:
    - build

- name: Clone source code
  ansible.builtin.git:
    repo: "{{ apps[0].repo }}"
    dest: "{{ git_folder.path }}"
    version: "{{ apps[0].version }}"
    clone: yes
    accept_hostkey: yes
    depth: 1
    key_file: "{{ playbook_dir }}/{{ ssh_private_key.dest }}"
  register: repo
  tags:
    - build

- name: Set Archive Path Variable
  set_fact:
    docker_tar_image: "{{ cache_folder }}/{{ apps[0].name }}.tar"
  tags:
    - build

- name: Build docker image
  community.docker.docker_image:
    build:
      path: "{{ git_folder.path }}"
    name: "{{ apps[0].name }}"
    tag: "{{ apps[0].version }}"
    source: local
    archive_path: "{{ docker_tar_image }}"
    state: present
  tags:
    - build

