---

- name: Create cache folder
  ansible.builtin.file:
    path: "{{ cache_folder }}"
    state: directory

- name: Create folders for source
  ansible.builtin.file:
    path: "{{ cache_folder }}/{{ item.name }}"
    state: directory
    recurse: yes
  loop: "{{ apps }}"
  register: git_folders

- name: Clone source code
  ansible.builtin.git:
    repo: "{{ item.repo }}"
    dest: "{{ git_folders.results[index].path }}"
    version: "{{ item.version }}"
    clone: yes
    accept_hostkey: yes
    depth: 1
    key_file: "{{ playbook_dir }}/ssh/id_ed25519"
  loop: "{{ apps }}"
  loop_control:
    index_var: index
  register: repo

- name: Build docker image
  community.docker.docker_image:
    build:
      path: "{{ git_folders.results[index].path }}"
    name: "{{ item.name }}"
    tag: "{{ item.version }}"
    source: build
    archive_path: "{{ cache_folder }}/{{ item.name }}.tar"
    state: present
  loop: "{{ apps }}"
  loop_control:
    index_var: index
