name: Continuous Deployment

on:
  # For debug
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          name: id_ed25519
          known_hosts: unnecessary

      - name: Create dot ENV file
        run: |
          echo DO_TOKEN=${{ secrets.DO_TOKEN }} >> .env
          echo "PROJECT_NAME=fastup-kit" >> .env

      - name: Create SSH files
        run: |
          mkdir ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" >> ./ssh/id_ed25519
          echo "${{ secrets.SSH_PUBLIC_KEY }}" >> ./ssh/id_ed25519.pub

      - name: Check files
        run: ls -al

      # - name: Run ansible-playbook
      #   run: ansible-playbook deploy-app.yml --tags "build" -i production.ini -i do_hosts.yml -vvvv
      #   env:
      #     PROJECT_NAME: fastup-kit
      #     DO_TOKEN: ${{ secrets.DO_TOKEN }}
      #     SSH_PUBLIC_KEY: ${{ secrets.SSH_PUBLIC_KEY }}
      #     SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
