name: Deploy All Applications

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          name: id_ed25519
          known_hosts: unnecessary

      # ATTENTION: will throw this .env file in running containers
      - name: Create dot ENV file
        run: |
          echo DO_TOKEN=${{ secrets.DO_TOKEN }} >> .env
          echo PROJECT_NAME=fastup-kit >> .env
          echo DO_TOKEN=${{ secrets.DO_TOKEN }} >> .env
          echo PG_CONNECTION_STRING=${{ secrets.PG_CONNECTION_STRING }} >> .env
          echo PG_PASSWORD=${{ secrets.PG_PASSWORD }} >> .env

      - name: Create SSH files
        run: |
          mkdir ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" >> ./ssh/id_ed25519
          echo "${{ secrets.SSH_PUBLIC_KEY }}" >> ./ssh/id_ed25519.pub

      - name: Build & Deploy microservices
        run: docker-compose -f docker-compose.yml -f configs/docker-compose.all-ms.yml up ansible

