name: Test

on:
  workflow_dispatch:

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - name: Setup new version
        id: bump-version
        uses: fastup-kit/bump-version@main
        with:
          file: 'vars/versions.yml'
          name: 'node-backend'
          version: 'v99.99.99'

      # Use the output from the `bump-version` step
      - name: Get the output time
        run: echo "The time was ${{ steps.bump-version.outputs.time }}"
